vinnilmg:
  client:
    address:
      url: http://localhost:8082/addresses
  kafka:
    host: localhost:9092
    group: vinnilmg

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cleanarch
