vinnilmg:
  client:
    address:
      url: http://localhost:8082/addresses
  kafka:
    host: localhost:9092
    group: vinnilmg

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: cleanarch